In [1]:
import numpy

In [3]:
flat_array = numpy.arange(1,10,0.5)
flat_array

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [4]:
flat_array.ptp()

8.5

In [5]:
flat_array.mean()

5.25

In [6]:
flat_array.sum()

94.5

In [9]:
numpy.median(flat_array)

5.25

In [10]:
one_dimensional = numpy.array([1,2,3,4,5,10])
one_dimensional

array([ 1,  2,  3,  4,  5, 10])

In [11]:
two_dimensional = numpy.array([
        [1,2,3],
        [1,4,6],
        [1,6,9],
        [2,1,0],
])
two_dimensional

array([[1, 2, 3],
       [1, 4, 6],
       [1, 6, 9],
       [2, 1, 0]])

In [12]:
two_dimensional[2]

array([1, 6, 9])

In [13]:
two_dimensional[2][1]

6

In [14]:
two_dimensional[2,1]

6

In [15]:
dir(two_dimensional)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_wrap__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__delslice__',
 '__div__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getslice__',
 '__gt__',
 '__hash__',
 '__hex__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__oct__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__rdivmod__',
 '__reduce__',
 

In [16]:
one_dimensional + 2

array([ 3,  4,  5,  6,  7, 12])

In [18]:
one_dimensional

array([ 1,  2,  3,  4,  5, 10])

In [19]:
plus_two = one_dimensional + 2

In [20]:
plus_two + one_dimensional

array([ 4,  6,  8, 10, 12, 22])

In [21]:
one_dimensional * 3

array([ 3,  6,  9, 12, 15, 30])

In [22]:
one_dimensional * plus_two

array([  3,   8,  15,  24,  35, 120])

In [23]:
(one_dimensional * plus_two).sum()

205

In [24]:
one_dimensional.dot(plus_two)

205

In [33]:
one_million_data_points = numpy.random.randint(0,1000,10000000)

In [34]:
one_million_data_points

array([823, 130, 471, ..., 625, 753,  41])

In [35]:
one_million_data_points.shape

(10000000,)

In [36]:
two_dimensional.shape

(4, 3)

In [37]:
one_million_data_points * 2

array([1646,  260,  942, ..., 1250, 1506,   82])

Let's compare the speed of doing that on a python list

In [38]:
one_million_list_points = list(one_million_data_points)

In [39]:
new_list = []
for i in range(len(one_million_data_points)):
    new_list.append(one_million_data_points[i]*2)
new_list

[1646,
 260,
 942,
 632,
 1306,
 1864,
 230,
 1278,
 1868,
 54,
 1662,
 662,
 560,
 166,
 550,
 50,
 626,
 114,
 798,
 1666,
 856,
 1798,
 1104,
 766,
 1620,
 690,
 1336,
 584,
 1612,
 98,
 78,
 1470,
 1532,
 1284,
 1038,
 1990,
 756,
 886,
 1368,
 630,
 1288,
 1666,
 1068,
 378,
 1670,
 1350,
 1810,
 1628,
 1258,
 496,
 516,
 946,
 1394,
 428,
 716,
 1540,
 332,
 1076,
 1846,
 1280,
 1454,
 636,
 1638,
 476,
 1628,
 1816,
 778,
 160,
 1160,
 1408,
 1694,
 1462,
 586,
 1322,
 1890,
 926,
 1878,
 860,
 562,
 768,
 478,
 1202,
 960,
 496,
 1580,
 950,
 1418,
 128,
 1984,
 606,
 664,
 1140,
 648,
 162,
 652,
 1978,
 402,
 552,
 596,
 1540,
 128,
 1480,
 1546,
 976,
 128,
 432,
 534,
 1052,
 1292,
 1540,
 1690,
 1000,
 96,
 1764,
 894,
 1938,
 540,
 530,
 266,
 56,
 392,
 1778,
 134,
 1328,
 522,
 1262,
 34,
 1562,
 768,
 504,
 972,
 1090,
 1824,
 1826,
 1188,
 96,
 202,
 1486,
 370,
 172,
 272,
 1546,
 1178,
 1416,
 766,
 1186,
 742,
 1940,
 990,
 1724,
 506,
 1554,
 1664,
 404,
 1346,
 9