In [1]:
# import numpy
# create array x
import numpy
x = numpy.arange(2,30,2)

In [3]:
# print the shape of x
x.shape

(14,)

In [13]:
# create a two dimensional array
y = numpy.array([[1,2,3],[4,5,6],[7,8,9],[4,6,8]])

In [14]:
# print shape of 2d array
y.shape

(4, 3)

In [15]:
# reshape the array to 2 x 6
y.reshape(2,6)

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 4, 6, 8]])

In [16]:
# reshape the array to 1 x 12
y.reshape(1,12)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 4, 6, 8]])

In [19]:
# transpose the array
numpy.transpose(y)

array([[1, 4, 7, 4],
       [2, 5, 8, 6],
       [3, 6, 9, 8]])

In [20]:
# indexing method 1
y[1:4:2]

array([[4, 5, 6],
       [4, 6, 8]])

In [23]:
# indexing method 2
y[0::-1]

array([[1, 2, 3]])

In [24]:
# indexing method 3
y[2][0:2]

array([7, 8])

In [12]:
# indexing method 4

In [11]:
# indexing method 5

In [10]:
# indexing method 6